import vscode from 'vscode';
import { Node, Parser, ParseException, ParseResult, Schema, SchemaValidator, ConditionalValidator, ValidationException, transformNodeToSchema, transformTemplateNodeToSchema } from '@stxt-lang/core';
import { AnalysisResult } from './AnalysisResult';
import { SchemaLoaderExtension, getSchemasForDocument } from './SchemaLoader';
import { diagnosticCollection } from '../extension';
import { TokenGeneratorObserver } from './TokenGeneratorObserver';
import { log } from './Log';

const LAST_ANALYSIS_BY_URI  = new Map<string, AnalysisResult>();

/** Code emitted by `SchemaValidator` when it cannot find the schema for a node's namespace. */
const SCHEMA_NOT_FOUND      = 'SCHEMA_NOT_FOUND';

/**
 * The analysis the providers use: the cached one if the document has already been
 * analyzed, otherwise a fresh one computed on the spot.
 *
 * The cold case is real and must be covered: VS Code asks for the semantic tokens as
 * soon as it paints the document, and that may arrive before the `onDidOpenTextDocument`
 * that analyzes it —or before the initial schema load, which is asynchronous, finishes—.
 * A provider that only looked at the cache would return nothing and the document would
 * stay **uncolored until it was edited**.
 *
 * @param document the document whose analysis is wanted.
 * @returns the analysis, or undefined if the extension is not activated yet (tests only).
 */
export function getAnalysis(document: vscode.TextDocument): AnalysisResult | undefined {
    const cached = LAST_ANALYSIS_BY_URI.get(document.uri.toString());

    if (cached || !diagnosticCollection) {
        return cached;
    }

    log.trace(`Cold analysis, not in cache: ${document.uri.toString()}`);
    return analysisDoc(document, diagnosticCollection);
}

export function analysisAllDocs(): void{
	for (const doc of vscode.workspace.textDocuments) {
		if (doc.languageId === 'stxt') {
			log.trace(`Re-analyzing open document: ${doc.uri.toString()}`);
			analysisDoc(doc, diagnosticCollection);
		}
	}
}

export function analysisDoc(document: vscode.TextDocument, diagnosticCollection: vscode.DiagnosticCollection): AnalysisResult {
    const diagnostics: vscode.Diagnostic[] = [];

    // Create the observer that generates tokens and nodeByLine during parsing
    const tokenObserver = new TokenGeneratorObserver();

    // Parse the document with schema validation. The provider is created with the
    // document's Uri: each document validates against its own resolution chain
    // (STXT-DISCOVERY-SPEC section 7), not against the union of everything loaded.
    const parser = new Parser();
    parser.registerObserver(tokenObserver);
    parser.registerValidator(new ConditionalValidator(new SchemaValidator(new SchemaLoaderExtension(document.uri))));
    const parseResult: ParseResult = parser.parseResult(document.getText());

    // Collect the tokens and nodeByLine generated by the observer
    const tokens = tokenObserver.getTokens();
    const nodeByLine = tokenObserver.getNodeByLine();
    const commentLines = tokenObserver.getCommentLines();
    const textLineByLineNumber = tokenObserver.getTextLineByLineNumber();

    // Convert errors to diagnostics
    const hasSchemas = getSchemasForDocument(document.uri).length > 0;

    for (const error of parseResult.getErrors()) {
        // STXT-SPEC §15 and §17.2: schemas are a separate, optional layer. If none is
        // loaded anywhere, a document with a namespace is not wrong, it just cannot be
        // validated: warning on every node would fill the file with squiggles.
        if (!hasSchemas && error.code === SCHEMA_NOT_FOUND) {
            continue;
        }

        const line = error.line > 0 ? error.line - 1 : 0;
        const lineText = document.lineAt(line).text;
        const range = new vscode.Range(line, 0, line, lineText.length);
        const severity = error instanceof ValidationException
            ? vscode.DiagnosticSeverity.Warning
            : vscode.DiagnosticSeverity.Error;
        diagnostics.push(new vscode.Diagnostic(range, `[${error.code}]: ${error.message}`, severity));
    }

    // Additional template and schema validations
    validateSpecialDocument(parseResult.getNodes(), diagnostics, "@stxt.template", "Template", transformTemplateNodeToSchema);
    validateSpecialDocument(parseResult.getNodes(), diagnostics, "@stxt.schema", "Schema", transformNodeToSchema);

    // End of diagnosis
    diagnosticCollection.set(document.uri, diagnostics);

    // Store the results
    const result: AnalysisResult = { tokens, nodeByLine, commentLines, textLineByLineNumber };
    LAST_ANALYSIS_BY_URI.set(document.uri.toString(), result);

    log.trace(`Analysis of ${document.uri.toString()}: ${tokens.length} tokens, ${diagnostics.length} diagnostics.`);
    return result;
}

function validateSpecialDocument(nodes: Node[], diagnostics: vscode.Diagnostic[], namespace: string, typeName: string,
     transformer: (node: Node) => Schema): void {
        
    nodes.forEach((node) => {
        if (node.getNamespace() === namespace) {
            try {
                transformer(node);
            } catch (e: unknown) {
                if (e instanceof ParseException) {
                    const line = e.line > 0 ? e.line - 1 : 0;
                    const range = new vscode.Range(line, 0, line, 100);
                    diagnostics.push(new vscode.Diagnostic(range, `${typeName} error [${e.code}]: ${e.message}`, vscode.DiagnosticSeverity.Error));
                } else if (e instanceof Error) {
                    const range = new vscode.Range(0, 0, 0, 100);
                    diagnostics.push(new vscode.Diagnostic(range, `Error: ${e.message}`, vscode.DiagnosticSeverity.Error));
                } else {
                    const range = new vscode.Range(0, 0, 0, 100);
                    diagnostics.push(new vscode.Diagnostic(range, `Unknown error: ${String(e)}`, vscode.DiagnosticSeverity.Error));
                }
            }
        }
    });
}